[tool.poetry]
name = "azacili_scheduler"
version = "0.1.0"
description = ""
authors = [
    "Ülgen Sarıkavak <work@ulgens.me>"
]

[tool.poetry.dev-dependencies]
django-debug-toolbar = "2.2"
django-sslserver = "0.22"
ipdb = "0.13.2"
ipython = "7.13.0"
fabric = "2.5.0"
factory-boy = "2.12.0"

[tool.poetry.dependencies]
python = "3.8.2"
beautifulsoup4= "4.8.2"
Django = "3.0.5"
django-braces = "1.14.0"
django-extensions = "2.2.9"
djangorestframework = "3.11.0"
gunicorn = "20.0.4"
html5lib = "1.0.1"
psycopg2-binary = "2.8.4"
raven = "6.10.0"
requests = "2.23.0"
social-auth-app-django = "3.1.0"
whitenoise = "5.0.1"

[build-system]
requires = ["poetry>=1.0.5"]
build-backend = "poetry.masonry.api"
