[tool.poetry]
name = "azacili_scheduler"
version = "0.1.0"
description = ""
authors = [
    "Ülgen Sarıkavak <work@ulgens.me>"
]

[tool.poetry.dev-dependencies]
django-debug-toolbar = "2.2"
django-sslserver = "0.22"
ipdb = "0.13.3"
ipython = "7.17.0"
fabric = "2.5.0"
factory-boy = "2.12.0"

[tool.poetry.dependencies]
python = "3.8.3"
beautifulsoup4= "4.9.1"
Django = "3.1"
django-braces = "1.14.0"
django-extensions = "3.0.5"
djangorestframework = "3.11.1"
gunicorn = "20.0.4"
html5lib = "1.1"
psycopg2-binary = "2.8.5"
raven = "6.10.0"
requests = "2.24.0"
social-auth-app-django = "4.0.0"
whitenoise = "5.1.0"

[build-system]
requires = ["poetry>=1.0.5"]
build-backend = "poetry.masonry.api"
